name: Deploy Node.js App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/node-cicd-demo/aws-ec2-cicd

            echo "Getting latest code..."
            git fetch origin
            git reset --hard origin/main

            echo "Installing dependencies..."
            npm install

            echo "Restarting application..."
            pm2 restart node-cicd-demo

            echo "Deployment completed!"